name: Metrics
on:
  schedule: [{ cron: "0 */2 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}
          user: revolunet
          use_prebuilt_image: yes
          template: classic
          config_timezone: Europe/Paris
          plugin_lines: yes
          plugin_stargazers: no
          config_padding: 16, 48
          # base
          base: header, activity, community, repositories, metadata
          repositories_forks: no
          repositories_affiliations: ""
          # languages
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          # habits
          plugin_habits: no
          # reactions
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot]
          plugin_reactions_limit: 200
          # followup
          plugin_followup: no
          # achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B # Display achievements with rank B or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_limit: 0 # Display all unlocked achievement matching threshold and secrets params
          # stackoverflow
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 174027
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 0
          # topics
          plugin_topics: yes
          plugin_topics_limit: 10
          plugin_topics_mode: icons
                  
